// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the ExpectedRackGroupUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedRackGroupUpdateRequest{}

// ExpectedRackGroupUpdateRequest Request data to update an existing Expected Rack Group.  For updates (`PATCH /expected-rack-group/{id}`), omit `id` or set it to `null` to use the ID from the URL path. A supplied string must match the URL path UUID in lowercase, hyphenated form. Empty strings, invalid UUIDs, and mismatched IDs are rejected with HTTP 400.  Provide a non-null value for at least one of `rackGroupId`, `topology`, `protocol`, `racks`, `name`, `description`, or `labels`. An empty object, a body containing only `id`, or a body with all seven fields omitted or set to `null` returns HTTP 400. Empty arrays for `racks`, empty objects for `labels`, and empty strings for `name` or `description` count as updates and clear those values.  The `rackGroupId` field is immutable on update. Providing its existing value alone satisfies the update requirement and still updates the modification time and sends the group to Core. Changing it returns HTTP 400.  Chassis identity and physical location information are conveyed via well-known label keys in `labels`: - `chassis.manufacturer`, `chassis.serial-number`, `chassis.model` - `location.region`, `location.datacenter`, `location.room`, `location.position`
type ExpectedRackGroupUpdateRequest struct {
	// Unique identifier (UUID) of the Expected Rack Group to update. Can be omitted or set to `null`. A supplied string must match the URL path UUID in lowercase, hyphenated form. Empty strings, invalid UUIDs, and mismatched IDs are rejected with HTTP 400.
	Id NullableString `json:"id,omitempty"`
	// Operator-supplied rack group identifier. Immutable on update: omit this field, send `null`, or provide the existing value without changing the identity. A changed value is rejected because Core uses rackGroupId as the identity key.
	RackGroupId NullableString `json:"rackGroupId,omitempty"`
	// Optional replacement topology identifier, non-blank and at most 128 characters.
	Topology NullableString `json:"topology,omitempty"`
	// Optional replacement rack fabric protocol, non-blank and at most 128 characters. `NVLINK_V6` enables GB-to-VR profile topology normalization.
	Protocol NullableString `json:"protocol,omitempty"`
	// Ordered racks and their devices. Rack IDs and device identity tuples must be unique across the group, with case-sensitive comparison. A provided array replaces the complete list; on PATCH, omission or null preserves it and [] clears it. On create, omission or null supplies an empty list.
	Racks []ExpectedRackGroupRack `json:"racks,omitempty"`
	// ASCII human-readable name, at most 256 characters. An empty string is allowed.
	Name NullableString `json:"name,omitempty" validate:"regexp=^[\\x00-\\x7F]*$"`
	// Human-readable description, at most 1024 UTF-8 bytes. An empty string is allowed.
	Description NullableString `json:"description,omitempty"`
	// User-defined key-value pairs with ASCII keys and Unicode values, each at most 255 UTF-8 bytes. Well-known keys (`chassis.*`, `location.*`) are used to convey chassis identity and physical location. Omission or null preserves existing labels; an empty object clears them. When labels is null, provide a non-null value for at least one of `rackGroupId`, `topology`, `protocol`, `racks`, `name`, or `description`.
	Labels map[string]string `json:"labels,omitempty"`
}

// NewExpectedRackGroupUpdateRequest instantiates a new ExpectedRackGroupUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedRackGroupUpdateRequest() *ExpectedRackGroupUpdateRequest {
	this := ExpectedRackGroupUpdateRequest{}
	return &this
}

// NewExpectedRackGroupUpdateRequestWithDefaults instantiates a new ExpectedRackGroupUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedRackGroupUpdateRequestWithDefaults() *ExpectedRackGroupUpdateRequest {
	this := ExpectedRackGroupUpdateRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackGroupUpdateRequest) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackGroupUpdateRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *ExpectedRackGroupUpdateRequest) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *ExpectedRackGroupUpdateRequest) SetId(v string) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *ExpectedRackGroupUpdateRequest) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *ExpectedRackGroupUpdateRequest) UnsetId() {
	o.Id.Unset()
}

// GetRackGroupId returns the RackGroupId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackGroupUpdateRequest) GetRackGroupId() string {
	if o == nil || IsNil(o.RackGroupId.Get()) {
		var ret string
		return ret
	}
	return *o.RackGroupId.Get()
}

// GetRackGroupIdOk returns a tuple with the RackGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackGroupUpdateRequest) GetRackGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RackGroupId.Get(), o.RackGroupId.IsSet()
}

// HasRackGroupId returns a boolean if a field has been set.
func (o *ExpectedRackGroupUpdateRequest) HasRackGroupId() bool {
	if o != nil && o.RackGroupId.IsSet() {
		return true
	}

	return false
}

// SetRackGroupId gets a reference to the given NullableString and assigns it to the RackGroupId field.
func (o *ExpectedRackGroupUpdateRequest) SetRackGroupId(v string) {
	o.RackGroupId.Set(&v)
}

// SetRackGroupIdNil sets the value for RackGroupId to be an explicit nil
func (o *ExpectedRackGroupUpdateRequest) SetRackGroupIdNil() {
	o.RackGroupId.Set(nil)
}

// UnsetRackGroupId ensures that no value is present for RackGroupId, not even an explicit nil
func (o *ExpectedRackGroupUpdateRequest) UnsetRackGroupId() {
	o.RackGroupId.Unset()
}

// GetTopology returns the Topology field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackGroupUpdateRequest) GetTopology() string {
	if o == nil || IsNil(o.Topology.Get()) {
		var ret string
		return ret
	}
	return *o.Topology.Get()
}

// GetTopologyOk returns a tuple with the Topology field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackGroupUpdateRequest) GetTopologyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Topology.Get(), o.Topology.IsSet()
}

// HasTopology returns a boolean if a field has been set.
func (o *ExpectedRackGroupUpdateRequest) HasTopology() bool {
	if o != nil && o.Topology.IsSet() {
		return true
	}

	return false
}

// SetTopology gets a reference to the given NullableString and assigns it to the Topology field.
func (o *ExpectedRackGroupUpdateRequest) SetTopology(v string) {
	o.Topology.Set(&v)
}

// SetTopologyNil sets the value for Topology to be an explicit nil
func (o *ExpectedRackGroupUpdateRequest) SetTopologyNil() {
	o.Topology.Set(nil)
}

// UnsetTopology ensures that no value is present for Topology, not even an explicit nil
func (o *ExpectedRackGroupUpdateRequest) UnsetTopology() {
	o.Topology.Unset()
}

// GetProtocol returns the Protocol field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackGroupUpdateRequest) GetProtocol() string {
	if o == nil || IsNil(o.Protocol.Get()) {
		var ret string
		return ret
	}
	return *o.Protocol.Get()
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackGroupUpdateRequest) GetProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Protocol.Get(), o.Protocol.IsSet()
}

// HasProtocol returns a boolean if a field has been set.
func (o *ExpectedRackGroupUpdateRequest) HasProtocol() bool {
	if o != nil && o.Protocol.IsSet() {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given NullableString and assigns it to the Protocol field.
func (o *ExpectedRackGroupUpdateRequest) SetProtocol(v string) {
	o.Protocol.Set(&v)
}

// SetProtocolNil sets the value for Protocol to be an explicit nil
func (o *ExpectedRackGroupUpdateRequest) SetProtocolNil() {
	o.Protocol.Set(nil)
}

// UnsetProtocol ensures that no value is present for Protocol, not even an explicit nil
func (o *ExpectedRackGroupUpdateRequest) UnsetProtocol() {
	o.Protocol.Unset()
}

// GetRacks returns the Racks field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackGroupUpdateRequest) GetRacks() []ExpectedRackGroupRack {
	if o == nil {
		var ret []ExpectedRackGroupRack
		return ret
	}
	return o.Racks
}

// GetRacksOk returns a tuple with the Racks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroupUpdateRequest) GetRacksOk() ([]ExpectedRackGroupRack, bool) {
	if o == nil || IsNil(o.Racks) {
		return nil, false
	}
	return o.Racks, true
}

// HasRacks returns a boolean if a field has been set.
func (o *ExpectedRackGroupUpdateRequest) HasRacks() bool {
	if o != nil && !IsNil(o.Racks) {
		return true
	}

	return false
}

// SetRacks gets a reference to the given []ExpectedRackGroupRack and assigns it to the Racks field.
func (o *ExpectedRackGroupUpdateRequest) SetRacks(v []ExpectedRackGroupRack) {
	o.Racks = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackGroupUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackGroupUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ExpectedRackGroupUpdateRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ExpectedRackGroupUpdateRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ExpectedRackGroupUpdateRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ExpectedRackGroupUpdateRequest) UnsetName() {
	o.Name.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackGroupUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackGroupUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ExpectedRackGroupUpdateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ExpectedRackGroupUpdateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ExpectedRackGroupUpdateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ExpectedRackGroupUpdateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackGroupUpdateRequest) GetLabels() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, an empty map otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroupUpdateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedRackGroupUpdateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedRackGroupUpdateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o ExpectedRackGroupUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedRackGroupUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.RackGroupId.IsSet() {
		toSerialize["rackGroupId"] = o.RackGroupId.Get()
	}
	if o.Topology.IsSet() {
		toSerialize["topology"] = o.Topology.Get()
	}
	if o.Protocol.IsSet() {
		toSerialize["protocol"] = o.Protocol.Get()
	}
	if o.Racks != nil {
		toSerialize["racks"] = o.Racks
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

type NullableExpectedRackGroupUpdateRequest struct {
	value *ExpectedRackGroupUpdateRequest
	isSet bool
}

func (v NullableExpectedRackGroupUpdateRequest) Get() *ExpectedRackGroupUpdateRequest {
	return v.value
}

func (v *NullableExpectedRackGroupUpdateRequest) Set(val *ExpectedRackGroupUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedRackGroupUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedRackGroupUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedRackGroupUpdateRequest(val *ExpectedRackGroupUpdateRequest) *NullableExpectedRackGroupUpdateRequest {
	return &NullableExpectedRackGroupUpdateRequest{value: val, isSet: true}
}

func (v NullableExpectedRackGroupUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedRackGroupUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
