// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExpectedMachineInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedMachineInterface{}

// ExpectedMachineInterface Expected interface declaration. Each supplied list entry replaces the corresponding declaration, so preserve all returned attributes when editing it. Core validates role, primary selection, and allocation against the Site configuration.
type ExpectedMachineInterface struct {
	// MAC address of the expected interface. Accepts six colon- or hyphen-separated octets in either case; stored and returned in uppercase colon-separated form, for example AA:BB:CC:DD:EE:FF. The same MAC may have separate IPv4 and IPv6 declarations.
	MacAddress string `json:"macAddress" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	// Optional NIC type. Use `CX9` for ConnectX-9 interfaces on Astra hosts.
	NicType NullableString `json:"nicType,omitempty"`
	// Optional fixed IPv4 or IPv6 address for the interface. REST preserves repeated MAC declarations without enforcing uniqueness by MAC and address family; Core applies allocation validation.
	FixedIp NullableString `json:"fixedIp,omitempty"`
	// Optional legacy mask string, forwarded unchanged. Omission or null clears it when replacing the declaration.
	FixedMask NullableString `json:"fixedMask,omitempty"`
	// Optional IPv4 or IPv6 gateway. Omission, null, or an empty string clears it when replacing the declaration.
	FixedGateway NullableString `json:"fixedGateway,omitempty"`
	// Host boot-interface selection. At most one Host interface per machine may set true. Omission or null clears the declaration. DpuOs and DpuBmc must omit it; HostBmc also accepts false.
	Primary NullableBool `json:"primary,omitempty"`
	// Optional segment constraint that takes precedence over nicType. Omission or null clears it. For explicit allocation policies and DPU roles it constrains relay-selected or fixed-address segments; legacy Host declarations without an explicit policy use it only for initial DHCP segment selection.
	NetworkSegmentType NullableString `json:"networkSegmentType,omitempty"`
	// Interface owner. On create, omission, null, or Unspecified means Host. On update, omission or null preserves a matching stored role; Unspecified resets it to Host. At most one HostBmc is allowed, with the same MAC as bmcMacAddress.
	Role NullableString `json:"role,omitempty"`
	// On create, omission, null, or Unspecified infers Fixed from fixedIp, otherwise Retained for HostBmc and Dynamic for other roles. On update, omission or null preserves a matching stored policy while fixedIp presence is unchanged; Unspecified resets inference. Fixed requires fixedIp; Dynamic and Retained forbid it. Explicit Fixed, inferred DPU Fixed, and inferred HostBmc Fixed with a segment constraint require a containing managed prefix; legacy Host or inferred HostBmc Fixed without a constraint may use static assignments. Retained keeps a DHCP-allocated address for the interface row lifetime.
	IpAllocation NullableString `json:"ipAllocation,omitempty"`
}

type _ExpectedMachineInterface ExpectedMachineInterface

// NewExpectedMachineInterface instantiates a new ExpectedMachineInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedMachineInterface(macAddress string) *ExpectedMachineInterface {
	this := ExpectedMachineInterface{}
	this.MacAddress = macAddress
	return &this
}

// NewExpectedMachineInterfaceWithDefaults instantiates a new ExpectedMachineInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedMachineInterfaceWithDefaults() *ExpectedMachineInterface {
	this := ExpectedMachineInterface{}
	return &this
}

// GetMacAddress returns the MacAddress field value
func (o *ExpectedMachineInterface) GetMacAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MacAddress
}

// GetMacAddressOk returns a tuple with the MacAddress field value
// and a boolean to check if the value has been set.
func (o *ExpectedMachineInterface) GetMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MacAddress, true
}

// SetMacAddress sets field value
func (o *ExpectedMachineInterface) SetMacAddress(v string) {
	o.MacAddress = v
}

// GetNicType returns the NicType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineInterface) GetNicType() string {
	if o == nil || IsNil(o.NicType.Get()) {
		var ret string
		return ret
	}
	return *o.NicType.Get()
}

// GetNicTypeOk returns a tuple with the NicType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineInterface) GetNicTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NicType.Get(), o.NicType.IsSet()
}

// HasNicType returns a boolean if a field has been set.
func (o *ExpectedMachineInterface) HasNicType() bool {
	if o != nil && o.NicType.IsSet() {
		return true
	}

	return false
}

// SetNicType gets a reference to the given NullableString and assigns it to the NicType field.
func (o *ExpectedMachineInterface) SetNicType(v string) {
	o.NicType.Set(&v)
}

// SetNicTypeNil sets the value for NicType to be an explicit nil
func (o *ExpectedMachineInterface) SetNicTypeNil() {
	o.NicType.Set(nil)
}

// UnsetNicType ensures that no value is present for NicType, not even an explicit nil
func (o *ExpectedMachineInterface) UnsetNicType() {
	o.NicType.Unset()
}

// GetFixedIp returns the FixedIp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineInterface) GetFixedIp() string {
	if o == nil || IsNil(o.FixedIp.Get()) {
		var ret string
		return ret
	}
	return *o.FixedIp.Get()
}

// GetFixedIpOk returns a tuple with the FixedIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineInterface) GetFixedIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FixedIp.Get(), o.FixedIp.IsSet()
}

// HasFixedIp returns a boolean if a field has been set.
func (o *ExpectedMachineInterface) HasFixedIp() bool {
	if o != nil && o.FixedIp.IsSet() {
		return true
	}

	return false
}

// SetFixedIp gets a reference to the given NullableString and assigns it to the FixedIp field.
func (o *ExpectedMachineInterface) SetFixedIp(v string) {
	o.FixedIp.Set(&v)
}

// SetFixedIpNil sets the value for FixedIp to be an explicit nil
func (o *ExpectedMachineInterface) SetFixedIpNil() {
	o.FixedIp.Set(nil)
}

// UnsetFixedIp ensures that no value is present for FixedIp, not even an explicit nil
func (o *ExpectedMachineInterface) UnsetFixedIp() {
	o.FixedIp.Unset()
}

// GetFixedMask returns the FixedMask field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineInterface) GetFixedMask() string {
	if o == nil || IsNil(o.FixedMask.Get()) {
		var ret string
		return ret
	}
	return *o.FixedMask.Get()
}

// GetFixedMaskOk returns a tuple with the FixedMask field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineInterface) GetFixedMaskOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FixedMask.Get(), o.FixedMask.IsSet()
}

// HasFixedMask returns a boolean if a field has been set.
func (o *ExpectedMachineInterface) HasFixedMask() bool {
	if o != nil && o.FixedMask.IsSet() {
		return true
	}

	return false
}

// SetFixedMask gets a reference to the given NullableString and assigns it to the FixedMask field.
func (o *ExpectedMachineInterface) SetFixedMask(v string) {
	o.FixedMask.Set(&v)
}

// SetFixedMaskNil sets the value for FixedMask to be an explicit nil
func (o *ExpectedMachineInterface) SetFixedMaskNil() {
	o.FixedMask.Set(nil)
}

// UnsetFixedMask ensures that no value is present for FixedMask, not even an explicit nil
func (o *ExpectedMachineInterface) UnsetFixedMask() {
	o.FixedMask.Unset()
}

// GetFixedGateway returns the FixedGateway field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineInterface) GetFixedGateway() string {
	if o == nil || IsNil(o.FixedGateway.Get()) {
		var ret string
		return ret
	}
	return *o.FixedGateway.Get()
}

// GetFixedGatewayOk returns a tuple with the FixedGateway field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineInterface) GetFixedGatewayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FixedGateway.Get(), o.FixedGateway.IsSet()
}

// HasFixedGateway returns a boolean if a field has been set.
func (o *ExpectedMachineInterface) HasFixedGateway() bool {
	if o != nil && o.FixedGateway.IsSet() {
		return true
	}

	return false
}

// SetFixedGateway gets a reference to the given NullableString and assigns it to the FixedGateway field.
func (o *ExpectedMachineInterface) SetFixedGateway(v string) {
	o.FixedGateway.Set(&v)
}

// SetFixedGatewayNil sets the value for FixedGateway to be an explicit nil
func (o *ExpectedMachineInterface) SetFixedGatewayNil() {
	o.FixedGateway.Set(nil)
}

// UnsetFixedGateway ensures that no value is present for FixedGateway, not even an explicit nil
func (o *ExpectedMachineInterface) UnsetFixedGateway() {
	o.FixedGateway.Unset()
}

// GetPrimary returns the Primary field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineInterface) GetPrimary() bool {
	if o == nil || IsNil(o.Primary.Get()) {
		var ret bool
		return ret
	}
	return *o.Primary.Get()
}

// GetPrimaryOk returns a tuple with the Primary field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineInterface) GetPrimaryOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Primary.Get(), o.Primary.IsSet()
}

// HasPrimary returns a boolean if a field has been set.
func (o *ExpectedMachineInterface) HasPrimary() bool {
	if o != nil && o.Primary.IsSet() {
		return true
	}

	return false
}

// SetPrimary gets a reference to the given NullableBool and assigns it to the Primary field.
func (o *ExpectedMachineInterface) SetPrimary(v bool) {
	o.Primary.Set(&v)
}

// SetPrimaryNil sets the value for Primary to be an explicit nil
func (o *ExpectedMachineInterface) SetPrimaryNil() {
	o.Primary.Set(nil)
}

// UnsetPrimary ensures that no value is present for Primary, not even an explicit nil
func (o *ExpectedMachineInterface) UnsetPrimary() {
	o.Primary.Unset()
}

// GetNetworkSegmentType returns the NetworkSegmentType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineInterface) GetNetworkSegmentType() string {
	if o == nil || IsNil(o.NetworkSegmentType.Get()) {
		var ret string
		return ret
	}
	return *o.NetworkSegmentType.Get()
}

// GetNetworkSegmentTypeOk returns a tuple with the NetworkSegmentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineInterface) GetNetworkSegmentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkSegmentType.Get(), o.NetworkSegmentType.IsSet()
}

// HasNetworkSegmentType returns a boolean if a field has been set.
func (o *ExpectedMachineInterface) HasNetworkSegmentType() bool {
	if o != nil && o.NetworkSegmentType.IsSet() {
		return true
	}

	return false
}

// SetNetworkSegmentType gets a reference to the given NullableString and assigns it to the NetworkSegmentType field.
func (o *ExpectedMachineInterface) SetNetworkSegmentType(v string) {
	o.NetworkSegmentType.Set(&v)
}

// SetNetworkSegmentTypeNil sets the value for NetworkSegmentType to be an explicit nil
func (o *ExpectedMachineInterface) SetNetworkSegmentTypeNil() {
	o.NetworkSegmentType.Set(nil)
}

// UnsetNetworkSegmentType ensures that no value is present for NetworkSegmentType, not even an explicit nil
func (o *ExpectedMachineInterface) UnsetNetworkSegmentType() {
	o.NetworkSegmentType.Unset()
}

// GetRole returns the Role field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineInterface) GetRole() string {
	if o == nil || IsNil(o.Role.Get()) {
		var ret string
		return ret
	}
	return *o.Role.Get()
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineInterface) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Role.Get(), o.Role.IsSet()
}

// HasRole returns a boolean if a field has been set.
func (o *ExpectedMachineInterface) HasRole() bool {
	if o != nil && o.Role.IsSet() {
		return true
	}

	return false
}

// SetRole gets a reference to the given NullableString and assigns it to the Role field.
func (o *ExpectedMachineInterface) SetRole(v string) {
	o.Role.Set(&v)
}

// SetRoleNil sets the value for Role to be an explicit nil
func (o *ExpectedMachineInterface) SetRoleNil() {
	o.Role.Set(nil)
}

// UnsetRole ensures that no value is present for Role, not even an explicit nil
func (o *ExpectedMachineInterface) UnsetRole() {
	o.Role.Unset()
}

// GetIpAllocation returns the IpAllocation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineInterface) GetIpAllocation() string {
	if o == nil || IsNil(o.IpAllocation.Get()) {
		var ret string
		return ret
	}
	return *o.IpAllocation.Get()
}

// GetIpAllocationOk returns a tuple with the IpAllocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineInterface) GetIpAllocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpAllocation.Get(), o.IpAllocation.IsSet()
}

// HasIpAllocation returns a boolean if a field has been set.
func (o *ExpectedMachineInterface) HasIpAllocation() bool {
	if o != nil && o.IpAllocation.IsSet() {
		return true
	}

	return false
}

// SetIpAllocation gets a reference to the given NullableString and assigns it to the IpAllocation field.
func (o *ExpectedMachineInterface) SetIpAllocation(v string) {
	o.IpAllocation.Set(&v)
}

// SetIpAllocationNil sets the value for IpAllocation to be an explicit nil
func (o *ExpectedMachineInterface) SetIpAllocationNil() {
	o.IpAllocation.Set(nil)
}

// UnsetIpAllocation ensures that no value is present for IpAllocation, not even an explicit nil
func (o *ExpectedMachineInterface) UnsetIpAllocation() {
	o.IpAllocation.Unset()
}

func (o ExpectedMachineInterface) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedMachineInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["macAddress"] = o.MacAddress
	if o.NicType.IsSet() {
		toSerialize["nicType"] = o.NicType.Get()
	}
	if o.FixedIp.IsSet() {
		toSerialize["fixedIp"] = o.FixedIp.Get()
	}
	if o.FixedMask.IsSet() {
		toSerialize["fixedMask"] = o.FixedMask.Get()
	}
	if o.FixedGateway.IsSet() {
		toSerialize["fixedGateway"] = o.FixedGateway.Get()
	}
	if o.Primary.IsSet() {
		toSerialize["primary"] = o.Primary.Get()
	}
	if o.NetworkSegmentType.IsSet() {
		toSerialize["networkSegmentType"] = o.NetworkSegmentType.Get()
	}
	if o.Role.IsSet() {
		toSerialize["role"] = o.Role.Get()
	}
	if o.IpAllocation.IsSet() {
		toSerialize["ipAllocation"] = o.IpAllocation.Get()
	}
	return toSerialize, nil
}

func (o *ExpectedMachineInterface) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"macAddress",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpectedMachineInterface := _ExpectedMachineInterface{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varExpectedMachineInterface)

	if err != nil {
		return err
	}

	*o = ExpectedMachineInterface(varExpectedMachineInterface)

	return err
}

type NullableExpectedMachineInterface struct {
	value *ExpectedMachineInterface
	isSet bool
}

func (v NullableExpectedMachineInterface) Get() *ExpectedMachineInterface {
	return v.value
}

func (v *NullableExpectedMachineInterface) Set(val *ExpectedMachineInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedMachineInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedMachineInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedMachineInterface(val *ExpectedMachineInterface) *NullableExpectedMachineInterface {
	return &NullableExpectedMachineInterface{value: val, isSet: true}
}

func (v NullableExpectedMachineInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedMachineInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
