// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExpectedRackGroupCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedRackGroupCreateRequest{}

// ExpectedRackGroupCreateRequest Request data to create a new Expected Rack Group.  The `rackGroupId` is an operator-supplied string identifier (UUID syntax is not required) that must be unique within the Site. Chassis identity and physical location information are conveyed via well-known label keys in `labels`: - `chassis.manufacturer`, `chassis.serial-number`, `chassis.model` - `location.region`, `location.datacenter`, `location.room`, `location.position`
type ExpectedRackGroupCreateRequest struct {
	// ID of the Site the Expected Rack Group belongs to
	SiteId string `json:"siteId"`
	// Operator-supplied identifier for the rack group (opaque string; UUID syntax is not required). Must be non-empty and unique within the Site.
	RackGroupId string `json:"rackGroupId"`
	// External group-level NVLink topology identifier, non-blank and at most 128 characters.
	Topology string `json:"topology"`
	// Rack fabric protocol, non-blank and at most 128 characters. `NVLINK_V6` enables GB-to-VR profile topology normalization.
	Protocol string `json:"protocol"`
	// Ordered racks and their devices. Rack IDs and device identity tuples must be unique across the group, with case-sensitive comparison. A provided array replaces the complete list; on PATCH, omission or null preserves it and [] clears it. On create, omission or null supplies an empty list.
	Racks []ExpectedRackGroupRack `json:"racks,omitempty"`
	// ASCII human-readable name, at most 256 characters. An empty string is allowed.
	Name NullableString `json:"name,omitempty" validate:"regexp=^[\\x00-\\x7F]*$"`
	// Human-readable description, at most 1024 UTF-8 bytes. An empty string is allowed.
	Description NullableString `json:"description,omitempty"`
	// User-defined key-value pairs with ASCII keys and Unicode values, each at most 255 UTF-8 bytes. Well-known keys (`chassis.*`, `location.*`) are used to convey chassis identity and physical location.
	Labels map[string]string `json:"labels,omitempty"`
}

type _ExpectedRackGroupCreateRequest ExpectedRackGroupCreateRequest

// NewExpectedRackGroupCreateRequest instantiates a new ExpectedRackGroupCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedRackGroupCreateRequest(siteId string, rackGroupId string, topology string, protocol string) *ExpectedRackGroupCreateRequest {
	this := ExpectedRackGroupCreateRequest{}
	this.SiteId = siteId
	this.RackGroupId = rackGroupId
	this.Topology = topology
	this.Protocol = protocol
	return &this
}

// NewExpectedRackGroupCreateRequestWithDefaults instantiates a new ExpectedRackGroupCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedRackGroupCreateRequestWithDefaults() *ExpectedRackGroupCreateRequest {
	this := ExpectedRackGroupCreateRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *ExpectedRackGroupCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroupCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *ExpectedRackGroupCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetRackGroupId returns the RackGroupId field value
func (o *ExpectedRackGroupCreateRequest) GetRackGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RackGroupId
}

// GetRackGroupIdOk returns a tuple with the RackGroupId field value
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroupCreateRequest) GetRackGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RackGroupId, true
}

// SetRackGroupId sets field value
func (o *ExpectedRackGroupCreateRequest) SetRackGroupId(v string) {
	o.RackGroupId = v
}

// GetTopology returns the Topology field value
func (o *ExpectedRackGroupCreateRequest) GetTopology() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Topology
}

// GetTopologyOk returns a tuple with the Topology field value
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroupCreateRequest) GetTopologyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Topology, true
}

// SetTopology sets field value
func (o *ExpectedRackGroupCreateRequest) SetTopology(v string) {
	o.Topology = v
}

// GetProtocol returns the Protocol field value
func (o *ExpectedRackGroupCreateRequest) GetProtocol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroupCreateRequest) GetProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protocol, true
}

// SetProtocol sets field value
func (o *ExpectedRackGroupCreateRequest) SetProtocol(v string) {
	o.Protocol = v
}

// GetRacks returns the Racks field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackGroupCreateRequest) GetRacks() []ExpectedRackGroupRack {
	if o == nil {
		var ret []ExpectedRackGroupRack
		return ret
	}
	return o.Racks
}

// GetRacksOk returns a tuple with the Racks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroupCreateRequest) GetRacksOk() ([]ExpectedRackGroupRack, bool) {
	if o == nil || IsNil(o.Racks) {
		return nil, false
	}
	return o.Racks, true
}

// HasRacks returns a boolean if a field has been set.
func (o *ExpectedRackGroupCreateRequest) HasRacks() bool {
	if o != nil && !IsNil(o.Racks) {
		return true
	}

	return false
}

// SetRacks gets a reference to the given []ExpectedRackGroupRack and assigns it to the Racks field.
func (o *ExpectedRackGroupCreateRequest) SetRacks(v []ExpectedRackGroupRack) {
	o.Racks = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackGroupCreateRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackGroupCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ExpectedRackGroupCreateRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ExpectedRackGroupCreateRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ExpectedRackGroupCreateRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ExpectedRackGroupCreateRequest) UnsetName() {
	o.Name.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackGroupCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackGroupCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ExpectedRackGroupCreateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ExpectedRackGroupCreateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ExpectedRackGroupCreateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ExpectedRackGroupCreateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedRackGroupCreateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, an empty map otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroupCreateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedRackGroupCreateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedRackGroupCreateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o ExpectedRackGroupCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedRackGroupCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["rackGroupId"] = o.RackGroupId
	toSerialize["topology"] = o.Topology
	toSerialize["protocol"] = o.Protocol
	if o.Racks != nil {
		toSerialize["racks"] = o.Racks
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

func (o *ExpectedRackGroupCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"rackGroupId",
		"topology",
		"protocol",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpectedRackGroupCreateRequest := _ExpectedRackGroupCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varExpectedRackGroupCreateRequest)

	if err != nil {
		return err
	}

	*o = ExpectedRackGroupCreateRequest(varExpectedRackGroupCreateRequest)

	return err
}

type NullableExpectedRackGroupCreateRequest struct {
	value *ExpectedRackGroupCreateRequest
	isSet bool
}

func (v NullableExpectedRackGroupCreateRequest) Get() *ExpectedRackGroupCreateRequest {
	return v.value
}

func (v *NullableExpectedRackGroupCreateRequest) Set(val *ExpectedRackGroupCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedRackGroupCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedRackGroupCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedRackGroupCreateRequest(val *ExpectedRackGroupCreateRequest) *NullableExpectedRackGroupCreateRequest {
	return &NullableExpectedRackGroupCreateRequest{value: val, isSet: true}
}

func (v NullableExpectedRackGroupCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedRackGroupCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
