// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the ExpectedRackGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedRackGroup{}

// ExpectedRackGroup An Expected Rack Group declares a group-level NVLink topology, racks, and expected device members. The `rackGroupId` is an operator-supplied string identifier (UUID syntax is not required) that uniquely identifies the group within the Site. Topology is supplied by the external inventory system.  Chassis identity and physical location information are conveyed via well-known label keys in `labels`: - `chassis.manufacturer`, `chassis.serial-number`, `chassis.model` - `location.region`, `location.datacenter`, `location.room`, `location.position`
type ExpectedRackGroup struct {
	// Unique identifier (UUID) for the Expected Rack Group
	Id *string `json:"id,omitempty"`
	// Operator-supplied identifier for the rack group (opaque string; UUID syntax is not required). Unique within a Site.
	RackGroupId *string `json:"rackGroupId,omitempty"`
	// ID of the Site the Expected Rack Group belongs to
	SiteId *string `json:"siteId,omitempty"`
	// Site details when requested through includeRelation; otherwise null.
	Site NullableSite `json:"site,omitempty"`
	// External group-level NVLink topology identifier.
	Topology *string `json:"topology,omitempty"`
	// Rack fabric protocol. Null only for declarations created before protocol became required.
	Protocol NullableString `json:"protocol,omitempty"`
	// Ordered racks and their devices. Arrays are always present, including empty lists. Rack IDs and device identity tuples are unique across the group, with case-sensitive comparison.
	Racks []ExpectedRackGroupRack `json:"racks,omitempty"`
	// Human-readable name of the Expected Rack Group
	Name *string `json:"name,omitempty"`
	// Human-readable description of the Expected Rack Group
	Description *string `json:"description,omitempty"`
	// User-defined key-value pairs for organizing and categorizing Expected Rack Groups. Well-known keys (`chassis.*`, `location.*`) are used to convey chassis identity and physical location.
	Labels map[string]string `json:"labels,omitempty"`
	// ISO 8601 datetime when the Expected Rack Group was created
	Created *time.Time `json:"created,omitempty"`
	// ISO 8601 datetime when the Expected Rack Group was last updated
	Updated *time.Time `json:"updated,omitempty"`
}

// NewExpectedRackGroup instantiates a new ExpectedRackGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedRackGroup() *ExpectedRackGroup {
	this := ExpectedRackGroup{}
	return &this
}

// NewExpectedRackGroupWithDefaults instantiates a new ExpectedRackGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedRackGroupWithDefaults() *ExpectedRackGroup {
	this := ExpectedRackGroup{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ExpectedRackGroup) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroup) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ExpectedRackGroup) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ExpectedRackGroup) SetId(v string) {
	o.Id = &v
}

// GetRackGroupId returns the RackGroupId field value if set, zero value otherwise.
func (o *ExpectedRackGroup) GetRackGroupId() string {
	if o == nil || IsNil(o.RackGroupId) {
		var ret string
		return ret
	}
	return *o.RackGroupId
}

// GetRackGroupIdOk returns a tuple with the RackGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroup) GetRackGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.RackGroupId) {
		return nil, false
	}
	return o.RackGroupId, true
}

// HasRackGroupId returns a boolean if a field has been set.
func (o *ExpectedRackGroup) HasRackGroupId() bool {
	if o != nil && !IsNil(o.RackGroupId) {
		return true
	}

	return false
}

// SetRackGroupId gets a reference to the given string and assigns it to the RackGroupId field.
func (o *ExpectedRackGroup) SetRackGroupId(v string) {
	o.RackGroupId = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *ExpectedRackGroup) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroup) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *ExpectedRackGroup) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *ExpectedRackGroup) SetSiteId(v string) {
	o.SiteId = &v
}

// GetSite returns the Site field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackGroup) GetSite() Site {
	if o == nil || IsNil(o.Site.Get()) {
		var ret Site
		return ret
	}
	return *o.Site.Get()
}

// GetSiteOk returns a tuple with the Site field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackGroup) GetSiteOk() (*Site, bool) {
	if o == nil {
		return nil, false
	}
	return o.Site.Get(), o.Site.IsSet()
}

// HasSite returns a boolean if a field has been set.
func (o *ExpectedRackGroup) HasSite() bool {
	if o != nil && o.Site.IsSet() {
		return true
	}

	return false
}

// SetSite gets a reference to the given NullableSite and assigns it to the Site field.
func (o *ExpectedRackGroup) SetSite(v Site) {
	o.Site.Set(&v)
}

// SetSiteNil sets the value for Site to be an explicit nil
func (o *ExpectedRackGroup) SetSiteNil() {
	o.Site.Set(nil)
}

// UnsetSite ensures that no value is present for Site, not even an explicit nil
func (o *ExpectedRackGroup) UnsetSite() {
	o.Site.Unset()
}

// GetTopology returns the Topology field value if set, zero value otherwise.
func (o *ExpectedRackGroup) GetTopology() string {
	if o == nil || IsNil(o.Topology) {
		var ret string
		return ret
	}
	return *o.Topology
}

// GetTopologyOk returns a tuple with the Topology field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroup) GetTopologyOk() (*string, bool) {
	if o == nil || IsNil(o.Topology) {
		return nil, false
	}
	return o.Topology, true
}

// HasTopology returns a boolean if a field has been set.
func (o *ExpectedRackGroup) HasTopology() bool {
	if o != nil && !IsNil(o.Topology) {
		return true
	}

	return false
}

// SetTopology gets a reference to the given string and assigns it to the Topology field.
func (o *ExpectedRackGroup) SetTopology(v string) {
	o.Topology = &v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedRackGroup) GetProtocol() string {
	if o == nil || IsNil(o.Protocol.Get()) {
		var ret string
		return ret
	}
	return *o.Protocol.Get()
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedRackGroup) GetProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Protocol.Get(), o.Protocol.IsSet()
}

// HasProtocol returns a boolean if a field has been set.
func (o *ExpectedRackGroup) HasProtocol() bool {
	if o != nil && o.Protocol.IsSet() {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given NullableString and assigns it to the Protocol field.
func (o *ExpectedRackGroup) SetProtocol(v string) {
	o.Protocol.Set(&v)
}

// SetProtocolNil sets the value for Protocol to be an explicit nil
func (o *ExpectedRackGroup) SetProtocolNil() {
	o.Protocol.Set(nil)
}

// UnsetProtocol ensures that no value is present for Protocol, not even an explicit nil
func (o *ExpectedRackGroup) UnsetProtocol() {
	o.Protocol.Unset()
}

// GetRacks returns the Racks field value if set, zero value otherwise.
func (o *ExpectedRackGroup) GetRacks() []ExpectedRackGroupRack {
	if o == nil || IsNil(o.Racks) {
		var ret []ExpectedRackGroupRack
		return ret
	}
	return o.Racks
}

// GetRacksOk returns a tuple with the Racks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroup) GetRacksOk() ([]ExpectedRackGroupRack, bool) {
	if o == nil || IsNil(o.Racks) {
		return nil, false
	}
	return o.Racks, true
}

// HasRacks returns a boolean if a field has been set.
func (o *ExpectedRackGroup) HasRacks() bool {
	if o != nil && !IsNil(o.Racks) {
		return true
	}

	return false
}

// SetRacks gets a reference to the given []ExpectedRackGroupRack and assigns it to the Racks field.
func (o *ExpectedRackGroup) SetRacks(v []ExpectedRackGroupRack) {
	o.Racks = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ExpectedRackGroup) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroup) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ExpectedRackGroup) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ExpectedRackGroup) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ExpectedRackGroup) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroup) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ExpectedRackGroup) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ExpectedRackGroup) SetDescription(v string) {
	o.Description = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedRackGroup) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, an empty map otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroup) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedRackGroup) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedRackGroup) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ExpectedRackGroup) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroup) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ExpectedRackGroup) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *ExpectedRackGroup) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *ExpectedRackGroup) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroup) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *ExpectedRackGroup) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *ExpectedRackGroup) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o ExpectedRackGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedRackGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.RackGroupId) {
		toSerialize["rackGroupId"] = o.RackGroupId
	}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if o.Site.IsSet() {
		toSerialize["site"] = o.Site.Get()
	}
	if !IsNil(o.Topology) {
		toSerialize["topology"] = o.Topology
	}
	if o.Protocol.IsSet() {
		toSerialize["protocol"] = o.Protocol.Get()
	}
	if !IsNil(o.Racks) {
		toSerialize["racks"] = o.Racks
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableExpectedRackGroup struct {
	value *ExpectedRackGroup
	isSet bool
}

func (v NullableExpectedRackGroup) Get() *ExpectedRackGroup {
	return v.value
}

func (v *NullableExpectedRackGroup) Set(val *ExpectedRackGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedRackGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedRackGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedRackGroup(val *ExpectedRackGroup) *NullableExpectedRackGroup {
	return &NullableExpectedRackGroup{value: val, isSet: true}
}

func (v NullableExpectedRackGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedRackGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
